# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jason Chemin
title: Phd student at LAAS-CNRS, Toulouse, France
email: jchemin [at] laas.fr
# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  JasonChmn
linkedin_username: jchemin


# Additional icon links
additional_links:
- icon: fa-brands fa-github
  url: https://github.com/JasonChmn
- icon: fa-brands fa-linkedin
  url: https://www.linkedin.com/in/jchemin

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jason and I'm a Phd student in Graphics and Machine learning. 
  I have a double master degree in Informatics and Telecommunications network from INSA (France) and Graphics in Seoul National University (South Korea).
  My research mainly focus on Reinforcement Learning for motion of characters, and I am interested in exploring new fields of application for machine learning !

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: "LEAS: Learning to steer a locomotion contact planner" - ICRA 2021
        link: https://ieeexplore.ieee.org/document/9561160
        description: | # this will include new lines to allow paragraphs
          A new RL steering method for terrain-aware navigation coupled to a sample-based contact planner.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: LAAS-CNRS, Toulouse, France
        caption: March - August 2019
        sub_title: Computer science engineer.
        description: | # this will include new lines to allow paragraphs
          Development of a library for Humanoid Path Planner software.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: LAAS-CNRS, Toulouse, France
        link: https://gepettoweb.laas.fr/index.php/Members/JasonChemin
        # link_text: boringcompany.com
        sub_title: Phd student
        caption: september 2019 - Present
        description: | # this will include new lines to allow paragraphs
        Thesis on contact planning for humanoid locomotion in the [MEMMO](https://www.memmo-project.eu/) project.
        I worked on a high-level approach with deep RL for contact planning. 
        Especially the development of a steering method with a terrain-aware navigation skills, generating a robot root trajectory before contact planning.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning some of my other interests and hobbies are : skiing, weightlifting and paragliding (soon) !

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]